import { returnsObj, returnsObjArabic } from "../returnMessages";

export const managementAppText = {
  "Log out": "Log out",
  Balance: "Balance",
  "Payment request": "Payment request",
  "Payment requests": "Payment requests",
  "Used balance": "Used balance",
  "Availabe Balance": "Availabe Balance",
  Add: "Add",
  Request: "Request",
  Validated: "Validated",
  Amount: "Amount",
  Cancel: "Cancel",
  "Load more": "Load more",
  Home: "Home",
  Orders: "Orders",
  "Active orders": "Active orders",
  "Order history": "Order history",
  "Management Information": "Management Information",
  "Log Out": "Log Out",
  "set store as opened": "set store as opened",
  Gram: "Gram",
  Milliliter: "Milliliter",
  "Construction materials": "Construction materials",
  Validate: "Validate",
  Transactions: "Transactions",
  script: "script",
  "Updating product": "Updating product",
  Done: "Done",
  Successful: "Successful",
  Error: "Error",
  "An Error occurred": "An Error occurred",
  Closing: "Closing",
  Opening: "Opening",
  "Management name": "Management name",
  Country: "Country",
  "Phone number": "Phone number",
  "Management address": "Management address",
  "Create management": "Create management",
  "Full name": "Full name",
  "Driver phone": "Driver phone",
  "Balance to add to the driver": "Balance to add to the driver",
  "Add driver": "Add driver",
  Search: "Search",
  "Add to wallet": "Add to wallet",
  Wallet: "Wallet",
  "Driver name": "Driver name",
  Actions: "Actions",
  "You don`t have drivers yet": "You don`t have drivers yet",
  "Cut to take from the driver": "Cut to take from the driver",
  "100%": "100%",
  "Update balance": "Update balance",
  "Remove driver": "Remove driver",
  "Driver Info": "Driver Info",
  "web-vitals": "web-vitals",
  "User Already Exists": "User Already Exists",
  "An account with this information already exists":
    "An account with this information already exists",
  "Confirmation code": "Confirmation code",
  "Confirm account": "Confirm account",
  "Signing up": "Signing up",
  "": "",
  "Signup successful": "Signup successful",
  "Check your Email for comfirmation": "Check your Email for comfirmation",
  Email: "Email",
  Password: "Password",
  Signup: "Signup",
  "have an account?": "have an account?",
  login: "login",
  "signup successful": "signup successful",
  "just login now": "just login now",
  "does not match email pattern": "does not match email pattern",
  "New Password": "New Password",
  Change: "Change",
  "sending confirmation email": "sending confirmation email",
  "email was sent": "email was sent",
  "an error occured": "an error occured",
  "Resend Confirmation email": "Resend Confirmation email",
  "Logging in": "Logging in",
  "Logged in": "Logged in",
  LogIn: "LogIn",
  "Not email pattern": "Not email pattern",
  "Forgot password": "Forgot password",
  "Management cut": "Management cut",
  "Update management": "Update management",
  "Merchant Id": "Merchant Id",
  "Terminal Id": "Terminal Id",
  "Secure key": "Secure key",
  Update: "Update",
  Disable: "Disable",
  Edit: "Edit",
  "Add keys": "Add keys",
  Tripoli: "Tripoli",
  Ajdabiya: "Ajdabiya",
  Zuwara: "Zuwara",
  Yafran: "Yafran",
  Nalut: "Nalut",
  Gharyan: "Gharyan",
  Al_Bayda: "Al_Bayda",
  Bani_Walid: "Bani_Walid",
  Al_Marj: "Al_Marj",
  Mizda: "Mizda",
  Benghazi: "Benghazi",
  Awbari: "Awbari",
  Tobruk: "Tobruk",
  Al_Khums: "Al_Khums",
  Murzuk: "Murzuk",
  Shahat: "Shahat",
  Sabratah: "Sabratah",
  Ghat: "Ghat",
  Sirte: "Sirte",
  Tajura: "Tajura",
  Misrata: "Misrata",
  Zawiya: "Zawiya",
  Sabha: "Sabha",
  Brak: "Brak",
  Ghadamis: "Ghadamis",
  Al_Abyar: "Al_Abyar",
  Tarhunah: "Tarhunah",
  Derna: "Derna",
  Waddan: "Waddan",
  Awjila: "Awjila",
  Suluq: "Suluq",
  Zelten: "Zelten",
  Qatrun: "Qatrun",
  Al_Qubbah: "Al_Qubbah",
  Tocra: "Tocra",
  Jalu: "Jalu",
  Zliten: "Zliten",
  Al_Jamīl: "Al_Jamīl",
  Brega: "Brega",
  Farzougha: "Farzougha",
  Sorman: "Sorman",
  Msallata: "Msallata",
  Kikla: "Kikla",
  infetch: "infetch",
  "content-type": "content-type",
  Restaurant: "Restaurant",
  Grocery: "Grocery",
  Clothes: "Clothes",
  Shoes: "Shoes",
  Stationery: "Stationery",
  Electronics: "Electronics",
  "Repair and spare parts": "Repair and spare parts",
  Furniture: "Furniture",
  "Watches, jewlery, and accessories": "Watches, jewlery, and accessories",
  "Mother and child accessories": "Mother and child accessories",
  "Cleaning meterials": "Cleaning meterials",
  Games: "Games",
  ...returnsObj,
};
export const managementAppArabicText = {
  "Log out": "تسجيل الخروج",
  Balance: "الرصيد",
  "Payment request": "طلب الدفع",
  "Payment requests": "طلبات الدفع",
  "Used balance": "الرصيد المستخدم",
  "Availabe Balance": "الرصيد المتاح",
  Add: "إضافة",
  Request: "طلب",
  Validated: "تم التحقق منه",
  Amount: "المبلغ",
  Cancel: "إلغاء",
  "Load more": "تحميل المزيد",
  Home: "الصفحة الرئيسية",
  Orders: "الطلبات",
  "Active orders": "الطلبات النشطة",
  "Order history": "سجل الطلبات",
  "Management Information": "معلومات الإدارة",
  "Log Out": "تسجيل الخروج",
  "set store as opened": "تعيين المتجر مفتوحًا",
  Gram: "جرام",
  Milliliter: "مل",
  "Construction materials": "مواد البناء",
  Validate: "تحقق",
  Transactions: "المعاملات",
  script: "نص",
  "Updating product": "تحديث المنتج",
  Done: "تم",
  Successful: "ناجح",
  Error: "خطأ",
  "An Error occurred": "حدث خطأ",
  Closing: "إغلاق",
  Opening: "فتح",
  "Management name": "اسم الإدارة",
  Country: "الدولة",
  "Phone number": "رقم الهاتف",
  "Management address": "عنوان الإدارة",
  "Create management": "إنشاء إدارة",
  "Full name": "الاسم الكامل",
  "Driver phone": "هاتف السائق",
  "Balance to add to the driver": "الرصيد الذي سيتم إضافته للسائق",
  "Add driver": "إضافة سائق",
  Search: "بحث",
  "Add to wallet": "إضافة إلى المحفظة",
  Wallet: "المحفظة",
  "Driver name": "اسم السائق",
  Actions: "الإجراءات",
  "You don`t have drivers yet": "لا يوجد لديك سائقون حتى الآن",
  "Cut to take from the driver": "النسبة المئوية التي سيتم خصمها من السائق",
  "100%": "100%",
  "Update balance": "تحديث الرصيد",
  "Remove driver": "إزالة السائق",
  "Driver Info": "معلومات السائق",
  "web-vitals": "مؤشرات الويب",
  "User Already Exists": "المستخدم موجود بالفعل",
  "An account with this information already exists":
    "حساب مسجل بهذه المعلومات موجود بالفعل",
  "Confirmation code": "رمز التأكيد",
  "Confirm account": "تأكيد الحساب",
  "Signing up": "جاري التسجيل",
  "": "",
  "Signup successful": "تم التسجيل بنجاح",
  "Check your Email for comfirmation":
    "يرجى التحقق من البريد الإلكتروني لتأكيد الحساب",
  Email: "البريد الإلكتروني",
  Password: "كلمة السر",
  Signup: "تسجيل",
  "have an account?": "لديك حساب؟",
  login: "تسجيل الدخول",
  "signup successful": "تم التسجيل بنجاح",
  "just login now": "تسجيل الدخول الآن",
  "does not match email pattern": "لا يتطابق مع نمط البريد الإلكتروني",
  "New Password": "كلمة السر الجديدة",
  Change: "تغيير",
  "sending confirmation email": "إرسال بريد إلكتروني للتأكيد",
  "email was sent": "تم إرسال البريد الإلكتروني",
  "an error occured": "حدث خطأ",
  "Resend Confirmation email": "إعادة إرسال بريد التأكيد",
  "Logging in": "جاري تسجيل الدخول",
  "Logged in": "تم تسجيل الدخول",
  LogIn: "تسجيل الدخول",
  "Not email pattern": "لا يطابق نمط البريد الإلكتروني",
  "Forgot password": "نسيت كلمة السر",
  "Management cut": "قطع الإدارة",
  "Update management": "تحديث الإدارة",
  "Merchant Id": "رقم التاجر",
  "Terminal Id": "رقم المحطة",
  "Secure key": "مفتاح الأمان",
  Update: "تحديث",
  Disable: "تعطيل",
  Edit: "تعديل",
  "Add keys": "إضافة مفاتيح",
  Tripoli: "طرابلس",
  Ajdabiya: "الأجدابية",
  Zuwara: "زوارة",
  Yafran: "يفرن",
  Nalut: "نالوت",
  Gharyan: "غريان",
  Al_Bayda: "البيضاء",
  Bani_Walid: "بني وليد",
  Al_Marj: "المرج",
  Mizda: "مزدة",
  Benghazi: "بنغازي",
  Awbari: "أوباري",
  Tobruk: "طبرق",
  Al_Khums: "الخمس",
  Murzuk: "مرزق",
  Shahat: "شحات",
  Sabratah: "صبراتة",
  Ghat: "غات",
  Sirte: "سرت",
  Tajura: "تاجوراء",
  Misrata: "مصراتة",
  Zawiya: "الزاوية",
  Sabha: "سبها",
  Brak: "براك الشاطئ",
  Ghadamis: "غدامس",
  Al_Abyar: "العبيار",
  Tarhunah: "ترهونة",
  Derna: "درنة",
  Waddan: "وادان",
  Awjila: "أوجلة",
  Suluq: "سلوق",
  Zelten: "زلطن",
  Qatrun: "قطرون",
  Al_Qubbah: "القبة",
  Tocra: "توكرة",
  Jalu: "جالو",
  Zliten: "زليتن",
  Al_Jamīl: "الجميل",
  Brega: "بريقة",
  Farzougha: "فرزوقة",
  Sorman: "سرمان",
  Msallata: "مسلاتة",
  Kikla: "كيكلا",
  infetch: "infetch",
  "content-type": "نوع المحتوى",
  Restaurant: "مطعم",
  Grocery: "بقالة",
  Clothes: "ملابس",
  Shoes: "أحذية",
  Stationery: "لوازم مكتبية",
  Electronics: "إلكترونيات",
  "Repair and spare parts": "إصلاح وقطع الغيار",
  Furniture: "أثاث",
  "Watches, jewlery, and accessories": "ساعات ومجوهرات وإكسسوارات",
  "Mother and child accessories": "إكسسوارات الأم والطفل",
  "Cleaning meterials": "مواد تنظيف",
  Games: "ألعاب",
  ...returnsObjArabic,
};
