import { returnsObj, returnsObjArabic } from "../returnMessages";

export const storeAppText = {
  "Order Settings": "Order Settings",
  "user id not found": "no user id",
  Confirm: "Confirm",
  "Rate and Confirm": "Rate and Confirm",
  "Confirm Pickup": "Confirm Pickup",
  Sales: "Sales",
  status: "status",
  Open: "Open",
  Closed: "Closed",
  "Close store": "Close store",
  "Open store": "Open store",
  "Log out": "Log out",
  Home: "Home",
  Orders: "Orders",
  "Active orders": "Active orders",
  "Order history": "Order history",
  Products: "Products",
  Collections: "Collections",
  Settings: "Settings",
  "Store Information": "Store Information",
  Payments: "Payments",
  "Log Out": "Log Out",
  "set store as opened": "set store as opened",
  "Collection name": "Collection name",
  "Collection description": "Collection description",
  Validate: "Validate",
  "Load more": "Load more",
  Transactions: "Transactions",
  Gram: "Gram",
  Milliliter: "Milliliter",
  "Construction materials": "Construction materials",
  script: "script",
  Closing: "Closing",
  Opening: "Opening",
  Done: "Done",
  Error: "Error",
  "An Error occurred": "An Error occurred",
  Price: "Price",
  "Cost Per Item": "Cost Per Item",
  "Prev price": "Prev price",
  Description: "Description",
  Title: "Title",
  "Weight in Kilo": "Weight in Kilo",
  "Is Active": "Is Active",
  "Measurement system": "Measurement system",
  Update: "Update",
  "Updating product": "Updating product",
  Successful: "Successful",
  "In Progress": "In Progress",
  Creating: "Creating",
  "New Collection": "New Collection",
  "automated collections must have at least one condition":
    "automated collections must have at least one condition",
  Create: "Create",
  ".": ".",
  "Create a collection": "Create a collection",
  All: "All",
  Active: "Active",
  Inactive: "Inactive",
  "Search for collections": "Search for collections",
  active: "active",
  inactive: "inactive",
  all: "all",
  conditions: "conditions",
  "No collections yet": "No collections yet",
  "with conditions": "with conditions",
  "no conditions": "no conditions",
  "Collection status": "Collection status",
  "Draft or InActive": "Draft or InActive",
  "is bigger than": "is bigger than",
  "is less than": "is less than",
  "is equal to": "is equal to",
  "is not equal to": "is not equal to",
  price: "price",
  title: "title",
  tag: "tag",
  weight: "weight",
  "All Conditions": "All Conditions",
  "Any Condition": "Any Condition",
  Delete: "Delete",
  "Add Condition": "Add Condition",
  "Deleting Collection": "Deleting Collection",
  "was Deleted successfully": "was Deleted successfully",
  "Delete collection": "Delete collection",
  "Manage collection products": "Manage collection products",
  "All products": "All products",
  "Collection Products": "Collection Products",
  More: "More",
  "Collection products": "Collection products",
  "StoreFront products": "StoreFront products",
  "Collection Type": "Collection Type",
  Manual: "Manual",
  "Automated. later update": "Automated. later update",
  Updating: "Updating",
  "was updated successfully": "was updated successfully",
  "Createing store": "Createing store",
  "store created": "store created",
  "Create Store": "Create Store",
  "Store Name": "Store Name",
  "Descripe what you serve in 4 words at most":
    "Descripe what you serve in 4 words at most",
  "store Phone": "store Phone",
  Country: "Country",
  City: "City",
  coords: "coords",
  "current coords": "current coords",
  Address: "Address",
  "Store Type": "Store Type",
  Restaurant: "Restaurant",
  grocery: "grocery",
  Clothes: "clothes",
  Shoes: "Shoes",
  Stationery: "Stationery",
  Electronics: "Electronics",
  "Repair and spare parts": "Repair and spare parts",
  "construction materials": "construction materials",
  furniture: "furniture",
  Bakery: "Bakery",
  Sweets: "Sweets",
  "Watches, jewwlry, and accessories": "Watches, jewwlry, and accessories",
  "Mother and child accessories": "Mother and child accessories",
  "Cleaning meterials": "Cleaning meterials",
  Games: "Games",
  "Meat store": "Meat store",
  "Submit store Info": "Submit store Info",
  "Create Product": "Create Product",
  "Search for products": "Search for products",
  Selected: "Selected",
  "Bulk Update": "Bulk Update",
  Options: "Options",
  Actions: "Actions",
  "you have no products yet": "you have no products yet",
  "signup successful": "signup successful",
  "just login now": "just login now",
  "does not match email pattern": "does not match email pattern",
  "Confirmation code": "Confirmation code",
  "New Password": "New Password",
  Change: "Change",
  "Confirm account": "Confirm account",
  "sending confirmation email": "sending confirmation email",
  "email was sent": "email was sent",
  "an error occured": "an error occured",
  "Resend Confirmation email": "Resend Confirmation email",
  "Logging in": "Logging in",
  "Logged in": "Logged in",
  Email: "Email",
  Password: "Password",
  LogIn: "LogIn",
  Signup: "Signup",
  "Not email pattern": "Not email pattern",
  "Forgot password": "Forgot password",
  "Bulk upload": "Bulk upload",
  "click here to pick a file": "click here to pick a file",
  Upload: "Upload",
  "make request": "make request",
  DownLoad: "DownLoad",
  Duplicate: "Duplicate",
  "Product Images": "Product Images",
  "product image": "product image",
  "Product status": "Product status",
  Add: "Add",
  collection: "collection",
  "Product barcode": "Product barcode",
  "Option Name": "Option Name",
  "Maximum Selectable": "Maximum Selectable",
  "Minimum Selectable": "Minimum Selectable",
  Required: "Required",
  X: "X",
  "Option Values": "Option Values",
  "Added cost": "Added cost",
  "Add value": "Add value",
  "add more": "add more",
  "Mesurement System": "Mesurement System",
  Kilo: "Kilo",
  Liter: "Liter",
  Unit: "Unit",
  "This Product Has Options": "This Product Has Options",
  "New Product": "New Product",
  Pricing: "Pricing",
  Currency: "Currency",
  "Compare at Price": "Compare at Price",
  "weight in Kilos": "weight in Kilos",
  "inserting new products": "inserting new products",
  "In progress": "In progress",
  "Products were added successfully": "Products were added successfully",
  a: "a",
  Deleting: "Deleting",
  "Deleteing in progress": "Deleteing in progress",
  Success: "Success",
  "Option name": "Option name",
  Value: "Value",
  "Added Price": "Added Price",
  "Add Option value": "Add Option value",
  "Add Option": "Add Option",
  Pending: "Pending",
  Accepted: "Accepted",
  Paid: "Paid",
  Preparing: "Preparing",
  Ready: "Ready",
  "No active orders now": "No active orders now",
  "Passport pic": "Passport pic",
  "Driver name": "Driver name",
  "Driver phone": "Driver phone",
  "Verify driver": "Verify driver",
  "Set driver as not verified": "Set driver as not verified",
  "Driver Info": "Driver Info",
  "Order paid": "Order paid",
  "Order not paid": "Order not paid",
  Name: "Name",
  Quantity: "Quantity",
  Image: "Image",
  Instructions: "Instructions",
  Control: "Control",
  "No options": "No options",
  "No instructions": "No instructions",
  "Reject Order": "Reject Order",
  "Accept Order": "Accept Order",
  "Order is ready": "Order is ready",
  Cancel: "Cancel",
  "Show Options": "Show Options",
  "No previous orders yet": "No previous orders yet",
  "Order total": "Order total",
  "Order sale fee": "Order sale fee",
  "Order Total after fee": "Order Total after fee",
  "QTY found": "QTY found",
  ID: "ID",
  "Payment method": "Payment method",
  Amount: "Amount",
  Validated: "Validated",
  "No transactions yet": "No transactions yet",
  "Show transactions": "Show transactions",
  "Set as Picked up": "Set as Picked up",
  "Not found": "Not found",
  Pickup: "Pickup",
  "Set product as inActive": "Set product as inActive",
  Rejecting: "Rejecting",
  "Order was rejected": "Order was rejected",
  Processing: "Processing",
  "Owner Info": "Owner Info",
  "first name": "first name",
  "last name": "last name",
  "phone number": "phone number",
  "Sadad API key": "Sadad API key",
  update: "update",
  "Account Payments": "Account Payments",
  "Number of months you want to subscribe for":
    "Number of months you want to subscribe for",
  "write the paying phone number": "write the paying phone number",
  "write your birth year": "write your birth year",
  "Resend OTP": "Resend OTP",
  "Send OTP": "Send OTP",
  "write the OTP here": "write the OTP here",
  "Make payment": "Make payment",
  "choose a payment method": "choose a payment method",
  Cost: "Cost",
  "Number of months": "Number of months",
  "Show payment gateway": "Show payment gateway",
  "Include local card fee in price": "Include local card fee in price",
  Edit: "Edit",
  "Merchant Id": "Merchant Id",
  "Terminal Id": "Terminal Id",
  "Secret key": "Secret key",
  Disable: "Disable",
  "Making Payment": "Making Payment",
  "Payment completed successfully": "Payment completed successfully",
  "Sending OTP": "Sending OTP",
  "OTP was sent successfully": "OTP was sent successfully",
  "Check your messages": "Check your messages",
  "resending OTP": "resending OTP",
  "OTP was resent successfully": "OTP was resent successfully",
  "User Already Exists": "User Already Exists",
  "An account with this information already exists":
    "An account with this information already exists",
  "Signing up": "Signing up",

  "Check your Email for comfirmation": "Check your Email for comfirmation",
  "have an account?": "have an account?",
  login: "login",
  token: "token",
  tokenId: "tokenId",
  "password was reset successfully": "password was reset successfully",
  "Reset password": "Reset password",
  "New password": "New password",
  "web-vitals": "web-vitals",
  "Updating Store Info": "Updating Store Info",
  "Store info was updated successfully": "Store info was updated successfully",
  "Store Image": "Store Image",
  "no image yet": "no image yet",
  "cleaning meterials": "cleaning meterials",
  "Update Store Info": "Update Store Info",
  "Store Info was successfully updated": "Store Info was successfully updated",
  Tripoli: "Tripoli",
  Ajdabiya: "Ajdabiya",
  Zuwara: "Zuwara",
  Yafran: "Yafran",
  Nalut: "Nalut",
  Gharyan: "Gharyan",
  Al_Bayda: "Al_Bayda",
  Bani_Walid: "Bani_Walid",
  Al_Marj: "Al_Marj",
  Mizda: "Mizda",
  Benghazi: "Benghazi",
  Awbari: "Awbari",
  Tobruk: "Tobruk",
  Al_Khums: "Al_Khums",
  Murzuk: "Murzuk",
  Shahat: "Shahat",
  Sabratah: "Sabratah",
  Ghat: "Ghat",
  Sirte: "Sirte",
  Tajura: "Tajura",
  Misrata: "Misrata",
  Zawiya: "Zawiya",
  Sabha: "Sabha",
  Brak: "Brak",
  Ghadamis: "Ghadamis",
  Al_Abyar: "Al_Abyar",
  Tarhunah: "Tarhunah",
  Derna: "Derna",
  Waddan: "Waddan",
  Awjila: "Awjila",
  Suluq: "Suluq",
  Zelten: "Zelten",
  Qatrun: "Qatrun",
  Al_Qubbah: "Al_Qubbah",
  Tocra: "Tocra",
  Jalu: "Jalu",
  Zliten: "Zliten",
  Al_Jamīl: "Al_Jamīl",
  Brega: "Brega",
  Farzougha: "Farzougha",
  Sorman: "Sorman",
  Msallata: "Msallata",
  Kikla: "Kikla",
  infetch: "infetch",
  "content-type": "content-type",
  Furniture: "Furniture",
  "Watches, jewlery, and accessories": "Watches, jewlery, and accessories",
  ...returnsObj
};

export const storeAppArabicText = {
  "Order Settings": "",
  "user id not found": "",
  Confirm: "تأكيد",
  "Rate and Confirm": "تقييم وتأكيد",
  "Confirm Pickup": "تأكيد الاستلام",
  Sales: "المبيعات",
  status: "الحالة",
  Open: "مفتوح",
  Closed: "مغلق",
  "Close store": "إغلاق المتجر",
  "Open store": "فتح المتجر",
  "Log out": "تسجيل الخروج",
  Home: "الرئيسية",
  Orders: "الطلبات",
  "Active orders": "الطلبات النشطة",
  "Order history": "سجل الطلبات",
  Products: "المنتجات",
  Collections: "المجموعات",
  Settings: "الإعدادات",
  "Store Information": "معلومات المتجر",
  Payments: "المدفوعات",
  "Log Out": "تسجيل الخروج",
  "set store as opened": "تعيين المتجر كمفتوح",
  "Collection name": "اسم المجموعة",
  "Collection description": "وصف المجموعة",
  Validate: "تحقق",
  "Load more": "تحميل المزيد",
  Transactions: "المعاملات",
  Gram: "جرام",
  Milliliter: "ملليلتر",
  "Construction materials": "مواد البناء",
  script: "النص البرمجي",
  Closing: "الإغلاق",
  Opening: "الفتح",
  Done: "تم",
  Error: "خطأ",
  "An Error occurred": "حدث خطأ",
  Price: "السعر",
  "Cost Per Item": "تكلفة القطعة",
  "Prev price": "السعر السابق",
  Description: "الوصف",
  Title: "العنوان",
  "Weight in Kilo": "الوزن بالكيلو",
  "Is Active": "نشط",
  "Measurement system": "نظام القياس",
  Update: "تحديث",
  "Updating product": "تحديث المنتج",
  Successful: "ناجح",
  "In Progress": "قيد التنفيذ",
  Creating: "إنشاء",
  "New Collection": "مجموعة جديدة",
  "automated collections must have at least one condition":
    "يجب أن تحتوي المجموعات الآلية على شرط واحد على الأقل",
  Create: "إنشاء",
  ".": ".",
  "Create a collection": "إنشاء مجموعة",
  All: "الكل",
  Active: "نشط",
  Inactive: "غير نشط",
  "Search for collections": "البحث عن المجموعات",
  active: "نشط",
  inactive: "غير نشط",
  all: "الكل",
  conditions: "الشروط",
  "No collections yet": "لا توجد مجموعات حتى الآن",
  "with conditions": "مع الشروط",
  "no conditions": "لا توجد شروط",
  "Collection status": "حالة المجموعة",
  "Draft or InActive": "مسودة أو غير نشط",
  "is bigger than": "أكبر من",
  "is less than": "أقل من",
  "is equal to": "يساوي",
  "is not equal to": "لا يساوي",
  price: "السعر",
  title: "العنوان",
  tag: "الوسم",
  weight: "الوزن",
  "All Conditions": "جميع الشروط",
  "Any Condition": "أي شرط",
  Delete: "حذف",
  "Add Condition": "إضافة شرط",
  "Deleting Collection": "حذف المجموعة",
  "was Deleted successfully": "تم حذفه بنجاح",
  "Delete collection": "حذف المجموعة",
  "Manage collection products": "إدارة منتجات المجموعة",

  "All products": "جميع المنتجات",
  "Collection Products": "منتجات المجموعة",
  More: "المزيد",
  "Collection products": "منتجات المجموعة",
  "StoreFront products": "منتجات المتجر",
  "Collection Type": "نوع المجموعة",
  Manual: "يدوي",
  "Automated. later update": "آلي. تحديث لاحق",
  Updating: "جاري التحديث",
  "was updated successfully": "تم التحديث بنجاح",
  "Createing store": "جار إنشاء المتجر",
  "store created": "تم إنشاء المتجر",
  "Create Store": "إنشاء متجر",
  "Store Name": "اسم المتجر",
  "Descripe what you serve in 4 words at most":
    "وصف ما تقدمه في 4 كلمات كحد أقصى",
  "store Phone": "هاتف المتجر",
  Country: "الدولة",
  City: "المدينة",
  coords: "الإحداثيات",
  "current coords": "الإحداثيات الحالية",
  Address: "العنوان",
  "Store Type": "نوع المتجر",
  Restaurant: "مطعم",
  grocery: "بقالة",
  Clothes: "ملابس",
  Shoes: "أحذية",
  Stationery: "قرطاسية",
  Electronics: "إلكترونيات",
  "Repair and spare parts": "إصلاح وقطع الغيار",
  "construction materials": "مواد البناء",
  furniture: "أثاث",
  Bakery: "مخبز",
  Sweets: "حلويات",
  "Watches, jewwlry, and accessories": "ساعات ومجوهرات وإكسسوارات",
  "Mother and child accessories": "إكسسوارات الأم والطفل",
  "Cleaning meterials": "مواد التنظيف",
  Games: "ألعاب",
  "Meat store": "محل للحوم",
  "Submit store Info": "إرسال معلومات المتجر",
  "Create Product": "إنشاء منتج",
  "Search for products": "البحث عن المنتجات",
  Selected: "المحددة",
  "Bulk Update": "تحديث جماعي",
  Options: "الخيارات",
  Actions: "الإجراءات",
  "you have no products yet": "لا يوجد لديك منتجات بعد",
  "signup successful": "تسجيل الدخول ناجح",

  "just login now": "تسجيل الدخول الآن",
  "does not match email pattern": "لا يتطابق مع نمط البريد الإلكتروني",
  "Confirmation code": "رمز التأكيد",
  "New Password": "كلمة مرور جديدة",
  Change: "تغيير",
  "Confirm account": "تأكيد الحساب",
  "sending confirmation email": "إرسال بريد التأكيد",
  "email was sent": "تم إرسال البريد الإلكتروني",
  "an error occured": "حدث خطأ",
  "Resend Confirmation email": "إعادة إرسال بريد التأكيد",
  "Logging in": "تسجيل الدخول",
  "Logged in": "تم تسجيل الدخول",
  Email: "البريد الإلكتروني",
  Password: "كلمة المرور",
  LogIn: "تسجيل الدخول",
  Signup: "التسجيل",
  "Not email pattern": "ليس نمط بريد إلكتروني",
  "Forgot password": "نسيت كلمة المرور",
  "Bulk upload": "تحميل جماعي",
  "click here to pick a file": "انقر هنا لاختيار ملف",
  Upload: "تحميل",
  "make request": "تقديم طلب",
  DownLoad: "تحميل",
  Duplicate: "تكرار",
  "Product Images": "صور المنتج",
  "product image": "صورة المنتج",
  "Product status": "حالة المنتج",
  Add: "إضافة",
  collection: "مجموعة",
  "Product barcode": "رمز الباركود للمنتج",
  "Option Name": "اسم الخيار",
  "Maximum Selectable": "الحد الأقصى للاختيار",
  "Minimum Selectable": "الحد الأدنى للاختيار",
  Required: "مطلوب",
  X: "X",
  "Option Values": "قيم الخيار",
  "Added cost": "التكلفة المضافة",
  "Add value": "إضافة قيمة",
  "add more": "إضافة المزيد",
  "Mesurement System": "نظام القياس",
  Kilo: "كيلو",
  Liter: "لتر",
  Unit: "وحدة",
  "This Product Has Options": "هذا المنتج لديه خيارات",
  "New Product": "منتج جديد",
  Pricing: "التسعير",
  Currency: "العملة",
  "Compare at Price": "السعر المقارن",
  "weight in Kilos": "الوزن بالكيلوغرامات",
  "inserting new products": "إدراج منتجات جديدة",
  "In progress": "قيد التنفيذ",
  "Products were added successfully": "تمت إضافة المنتجات بنجاح",
  a: "أ",
  Deleting: "حذف",
  "Deleteing in progress": "جاري الحذف",
  Success: "نجاح",
  "Option name": "اسم الخيار",
  Value: "القيمة",
  "Added Price": "السعر المضاف",
  "Add Option value": "إضافة قيمة الخيار",
  "Add Option": "إضافة خيار",
  Pending: "قيد الانتظار",
  Accepted: "تم القبول",
  Paid: "تم الدفع",
  Preparing: "قيد التحضير",
  Ready: "جاهز",
  "No active orders now": "لا يوجد طلبات نشطة حاليًا",
  "Passport pic": "صورة جواز السفر",
  "Driver name": "اسم السائق",
  "Driver phone": "رقم هاتف السائق",
  "Verify driver": "تحقق من السائق",
  "Set driver as not verified": "تعيين السائق كغير محقق",
  "Driver Info": "معلومات السائق",
  "Order paid": "تم دفع الطلب",
  "Order not paid": "الطلب لم يتم دفعه",
  Name: "الاسم",
  Quantity: "الكمية",
  Image: "الصورة",
  Instructions: "التعليمات",
  Control: "التحكم",
  "No options": "لا توجد خيارات",
  "No instructions": "لا توجد تعليمات",
  "Reject Order": "رفض الطلب",
  "Accept Order": "قبول الطلب",
  "Order is ready": "الطلب جاهز",
  Cancel: "إلغاء",
  "Show Options": "عرض الخيارات",
  "No previous orders yet": "لا توجد طلبات سابقة بعد",
  "Order total": "إجمالي الطلب",
  "Order sale fee": "رسوم بيع الطلب",
  "Order Total after fee": "إجمالي الطلب بعد الرسوم",
  "QTY found": "تم العثور على الكمية",
  ID: "معرف",
  "Payment method": "طريقة الدفع",
  Amount: "المبلغ",
  Validated: "موثق",
  "No transactions yet": "لا توجد معاملات حتى الآن",
  "Show transactions": "إظهار المعاملات",
  "Set as Picked up": "تعيين كما تم الاستلام",
  "Not found": "غير موجود",
  Pickup: "الاستلام",
  "Set product as inActive": "تعيين المنتج كغير نشط",
  Rejecting: "رفض",
  "Order was rejected": "تم رفض الطلب",
  Processing: "جاري المعالجة",
  "Owner Info": "معلومات المالك",
  "first name": "الاسم الأول",
  "last name": "اسم العائلة",
  "phone number": "رقم الهاتف",
  "Sadad API key": "مفتاح API السداد",
  update: "تحديث",
  "Account Payments": "مدفوعات الحساب",
  "Number of months you want to subscribe for":
    "عدد الشهور التي تريد الاشتراك فيها",
  "write the paying phone number": "اكتب رقم الهاتف الخاص بالدفع",
  "write your birth year": "اكتب سنة ميلادك",
  "Resend OTP": "إعادة إرسال OTP",
  "Send OTP": "إرسال OTP",
  "write the OTP here": "اكتب OTP هنا",
  "Make payment": "إجراء الدفع",
  "choose a payment method": "اختر طريقة الدفع",
  Cost: "التكلفة",
  "Number of months": "عدد الشهور",
  "Show payment gateway": "عرض بوابة الدفع",
  "Include local card fee in price": "تضمين رسوم بطاقة الدفع المحلية في السعر",
  Edit: "تعديل",
  "Merchant Id": "معرف التاجر",
  "Terminal Id": "معرف المحطة",
  "Secret key": "المفتاح السري",
  Disable: "تعطيل",
  "Making Payment": "جاري الدفع",
  "Payment completed successfully": "تم الدفع بنجاح",
  "Sending OTP": "إرسال رمز التحقق",
  "OTP was sent successfully": "تم إرسال رمز التحقق بنجاح",
  "Check your messages": "تحقق من رسائلك",
  "resending OTP": "إعادة إرسال رمز التحقق",
  "OTP was resent successfully": "تم إعادة إرسال رمز التحقق بنجاح",
  "User Already Exists": "المستخدم موجود بالفعل",
  "An account with this information already exists":
    "يوجد حساب بالفعل بهذه المعلومات",
  "Signing up": "جاري التسجيل",

  "Check your Email for comfirmation": "تحقق من بريدك الإلكتروني للتأكيد",
  "have an account?": "هل لديك حساب؟",
  login: "تسجيل الدخول",
  token: "الرمز البرمجي",
  tokenId: "معرف الرمز البرمجي",
  "password was reset successfully": "تمت إعادة تعيين كلمة المرور بنجاح",
  "Reset password": "إعادة تعيين كلمة المرور",
  "New password": "كلمة مرور جديدة",
  "web-vitals": "مؤشرات الويب",
  "Updating Store Info": "جاري تحديث معلومات المتجر",
  "Store info was updated successfully": "تم تحديث معلومات المتجر بنجاح",
  "Store Image": "صورة المتجر",
  "no image yet": "لا يوجد صورة حتى الآن",
  "cleaning meterials": "مواد التنظيف",
  "Update Store Info": "تحديث معلومات المتجر",
  "Store Info was successfully updated": "تم تحديث معلومات المتجر بنجاح",
  Tripoli: "طرابلس",
  Ajdabiya: "أجدابيا",
  Zuwara: "زوارة",
  Yafran: "يفرن",
  Nalut: "نالوت",
  Gharyan: "غريان",
  Al_Bayda: "البيضاء",
  Bani_Walid: "بني وليد",
  Al_Marj: "المرج",
  Mizda: "مزدة",
  Benghazi: "بنغازي",
  Awbari: "أوباري",
  Tobruk: "طبرق",
  Al_Khums: "الخمس",
  Murzuk: "مرزق",
  Shahat: "شحات",
  Sabratah: "صبراتة",
  Ghat: "غات",
  Sirte: "سرت",
  Tajura: "تاجوراء",
  Misrata: "مصراتة",
  Zawiya: "الزاوية",
  Sabha: "سبها",
  Brak: "البراك الشاطئ",
  Ghadamis: "غدامس",
  Al_Abyar: "الأبيار",
  Tarhunah: "ترهونة",
  Derna: "درنة",
  Waddan: "وادان",
  Awjila: "أوجلة",
  Suluq: "سلوق",
  Zelten: "زلتن",
  Qatrun: "قطران",
  Al_Qubbah: "القبة",
  Tocra: "طكرة",
  Jalu: "جالو",
  Zliten: "زليتن",
  Al_Jamīl: "الجميل",
  Brega: "البريقة",
  Farzougha: "فرزوقة",
  Sorman: "صرمان",
  Msallata: "مسلاتة",
  Kikla: "ككلة",
  infetch: "infetch",
  "content-type": "نوع المحتوى",
  Furniture: "أثاث",
  "Watches, jewlery, and accessories": "الساعات والمجوهرات والإكسسوارات",
  ...returnsObjArabic
};
