export const ar = {
  translation: {
    "Have an account already?": "هل لديك حساب بالفعل؟",
    "Common questions": "اسئلة شائعة",
    "Start selling": "ابدأ البيع",
    "Start shopping": "ابدأ التسوق",
    "Grow your business and reach new customers by partnering with us":
      "قم بتطوير عملك والوصول إلى عملاء جدد من خلال شراكتك معنا",
    "Sell on hyfn": "بيع على منصة هايفن",
    "Order anything for delivery or pickup": "اطلب أي شيء للتوصيل أو الاستلام",
    "Whatever you want from local stores, brought right to your door":
      "ما يناسبك من المتاجر المحلية، يصلك مباشرة إلى باب منزلك",
    "This action is not recommended": "هذا الإجراء غير مستحسن",
    Cancel: "إلغاء",
    Cancal: "إلغاء",
    Confirm: "تأكيد",
    "Rate and Confirm": "تقييم وتأكيد",
    "Confirm Delivery": "تأكيد التسليم",
    "Scan QR code": "مسح رمز الاستجابة السريعة",
    "Confirm pickup": "تأكيد الاستلام",
    ",": "،",
    City: "المدينة",
    "Get current coords": "الحصول على الإحداثيات الحالية",
    "set Location": "تحديد الموقع",
    "explore products and stores in your city":
      "استكشاف المنتجات والمتاجر في مدينتك",
    "Active Orders": "الطلبات النشطة",
    History: "التاريخ",
    Balance: "الرصيد",
    "Add instructions to this item": "إضافة تعليمات لهذا المنتج",
    "Add Instructions": "إضافة تعليمات",
    Instructions: "التعليمات",
    Home: "الصفحة الرئيسية",
    Orders: "الطلبات",
    "account settings": "إعدادات الحساب",
    "how the app works": "كيفية عمل التطبيق",
    help: "المساعدة",
    addresses: "العناوين",
    "Become a partner store": "أصبح شريكًا للمتجر",
    Password: "كلمة المرور",
    Email: "البريد الالكتروني ",
    LogOut: "تسجيل الخروج",
    Signup: "التسجيل",
    LogIn: "تسجيل الدخول",
    Pickup: "استلام",
    Explore: "استكشاف",
    Tripoli: "طرابلس",
    Ajdabiya: "أجدابيا",
    Zuwara: "زوارة",
    Yafran: "يفرن",
    Nalut: "نالوت",
    Gharyan: "غريان",
    Al_Bayda: "البيضاء",
    Bani_Walid: "بني وليد",
    Al_Marj: "المرج",
    Mizda: "مزدة",
    Benghazi: "بنغازي",
    Awbari: "أوباري",
    Tobruk: "طبرق",
    Al_Khums: "الخمس",
    Murzuk: "مرزق",
    Shahat: "شحات",
    Sabratah: "صبراته",
    Ghat: "غات",
    Sirte: "سرت",
    Tajura: "تاجوراء",
    Misrata: "مصراتة",
    Zawiya: "الزاوية",
    Sabha: "سبها",
    Brak: "براك",
    Ghadamis: "غدامس",
    Al_Abyar: "الأبيار",
    Tarhunah: "ترهونة",
    Derna: "درنة",
    Waddan: "وادان",
    Awjila: "أوجلة",
    Suluq: "سلوق",
    Zelten: "زلتن",
    Qatrun: "قطرون",
    Al_Qubbah: "القبة",
    Tocra: "طبرق",
    Jalu: "جالو",
    Zliten: "زليتن",
    Al_Jamīl: "الجميل",
    Brega: "بريقة",
    Farzougha: "الفرزوقة",
    Sorman: "صرمان",
    Msallata: "مسلاتة",
    Kikla: "كيكلة",
    "Choose a payment method": "اختر طريقة الدفع",
    Name: "الاسم",
    "QTY found": "الكمية الموجودة",
    Image: "الصورة",
    "Order total": "مجموع الطلب",
    "Service fee": "رسوم الخدمة",
    "Delivery fee": "رسوم التوصيل",
    "Order Total after fee": "مجموع الطلب بعد الرسوم",
    Pay: "ادفع",
    "Your balance is suffictient for making this order":
      "رصيدك كافي لإتمام الطلب",
    "choose a payment method": "اختر طريقة الدفع",
    "Set as Picked up": "تم استلامه",
    "Not found": "غير موجود",
    Store: "المتجر",
    Amount: "المبلغ",
    Validated: "تم التحقق",
    Validate: "تحقق",
    "Load more": "تحميل المزيد",
    Transactions: "المعاملات",
    "Store Name": "اسم المتجر",
    "Store Phone": "هاتف المتجر",
    "More info": "المزيد من المعلومات",
    "Construction materials": "مواد البناء",
    "Only restuarants can take pickup orders":
      "يمكن للمطاعم فقط تلقي طلبات الاستلام",
    "": "",
    "In progress": "قيد التقدم",
    Processing: "معالجة",
    Success: "نجاح",
    "An Error occurred": "حدث خطأ",
    script: "نص",
    "change password": "تغيير كلمة المرور",
    "Set Account Info": "تعيين معلومات الحساب",
    "updating user info": "تحديث معلومات المستخدم",
    "In Progress": "قيد التنفيذ",
    "User info successfully updated": "تم تحديث معلومات المستخدم بنجاح",
    Successful: "ناجح",
    Label: "ملصق",
    Coordinates: "إحداثيات",
    "Current Coords": "الإحداثيات الحالية",
    "Location description": "وصف الموقع",
    Save: "حفظ",
    Delete: "حذف",
    Update: "تحديث",
    "Add address": "إضافة عنوان",
    Delivery: "توصيل",
    weight: "الوزن",
    Remove: "إزالة",
    "Place Order": "تقديم الطلب",
    "edit if you want": "تحرير إذا كنت تريد",
    "write the paying phone number": "أدخل رقم الهاتف المدفوع",
    "write your birth year": "أدخل سنة ميلادك",
    "Resend OTP": "إعادة إرسال OTP",
    "Send OTP": "إرسال OTP",
    "write the OTP here": "أدخل OTP هنا",
    "Make payment": "إجراء الدفع",
    "your cart is empty! ... go fill it up":
      "عربة التسوق الخاصة بك فارغة! ... املأها",
    "Clear cart": "مسح السلة",
    "Order total must exceed 50": "إجمالي الطلب يجب أن يتجاوز 50",
    Edit: "تحرير",
    "Delivery Location": "موقع التسليم",
    "set your current location": "تحديد موقعك الحالي",
    Location: "الموقع",
    Addresses: "العناوين",
    "Location details": "تفاصيل الموقع",
    "Pick Date": "اختر التاريخ",
    request: "طلب",
    "Next step": "الخطوة التالية",
    Subtotal: "المجموع الفرعي",
    Total: "المجموع",
    "Orders are not optimized for city-to-city deliveries":
      "الطلبات ليست محسّنة لتسليم المدينة إلى المدينة",
    "OTP sent": "تم إرسال OTP",
    "check your messages": "تحقق من رسائلك",
    "OTP was resent": "تم إعادة إرسال OTP",
    "payment complete": "اكتمل الدفع",
    "your wallet was added x amount": "تم إضافة x إلى محفظتك",
    Error: "خطأ",
    Results: "النتائج",
    Nearby: "القريبة",
    Reset: "إعادة تعيين",
    More: "المزيد",
    Submit: "إرسال",
    "successful signup": "تسجيل الدخول بنجاح",
    "just log into your account now ": "سجّل دخولك إلى حسابك الآن",
    "does not match email pattern": "لا يتطابق مع نمط البريد الإلكتروني",
    "Confirmation code": "رمز التأكيد",
    "New Password": "كلمة المرور الجديدة",
    Change: "تغيير",
    "Confirm account": "تأكيد الحساب",
    "sending confirmation email": "إرسال رسالة تأكيد",
    "email was sent": "تم إرسال البريد الإلكتروني",
    "an error occured": "حدث خطأ",
    "Resend Confirmation email": "إعادة إرسال رسالة التأكيد",
    "Logging in": "تسجيل الدخول",
    "Logged in": "تم تسجيل الدخول",

    "Not email pattern": "لا يتطابق مع نمط البريد الإلكتروني",
    "Forgot password": "نسيت كلمة المرور",
    Groceries: "المواد الغذائية",
    "Cleaning supplies": "مستلزمات التنظيف",
    Makeup: "مستحضرات التجميل",
    Clothes: "الملابس",
    Restaurants: "المطاعم",
    Malls: "المراكز التجارية",
    "Food Supplements": "مكملات غذائية",
    "Meat store": "محل اللحوم",
    Pharmasies: "الصيدليات",
    clothes: "الملابس",
    Index: "فهرس",
    Quantity: "الكمية",
    Options: "الخيارات",
    "No options": "لا يوجد خيارات",
    cancel: "إلغاء",
    "Passport pic": "صورة جواز السفر",
    "Driver Info": "معلومات السائق",
    "Management Info": "معلومات الإدارة",
    Report: "تقرير",
    Show: "عرض",
    rate: "تقييم",
    "No previous orders yet": "ليس لديك طلبات سابقة حتى الآن",
    "Order sale fee": "رسوم بيع الطلب",
    "Pay Store": "دفع المتجر",
    "Pay Service fee": "رسوم الخدمة",
    "Set as Delivered": "تم التوصيل",
    "Your Report": "تقريرك",
    ID: "المعرّف",
    "Payment method": "طريقة الدفع",
    Copied: "تم النسخ",
    Price: "السعر",
    Accept: "قبول",
    Proposals: "العروض",
    "in your cart": "في سلة التسوق الخاصة بك",
    and: "و",
    "set in Cart": "تمت الإضافة إلى سلة التسوق",
    "User Already Exists": "المستخدم موجود مسبقاً",
    "An account with this information already exists":
      "هناك حساب مسجل مسبقاً باستخدام هذه المعلومات",
    "Signing up": "جاري التسجيل",
    "Check your Email for confirmation Email":
      "يرجى التحقق من البريد الإلكتروني لتأكيد الحساب",
    "Signed up successfully": "تم التسجيل بنجاح",
    "An Error occurred": "حدث خطأ",
    "have an account?": "لديك حساب؟",
    Login: "تسجيل الدخول",
    m: "م",
    km: "كم",
    ratings: "التقييمات",
    Open: "مفتوح",
    Closed: "مغلق",
    "show all": "عرض الكل",
    token: "رمز المصادقة",
    tokenId: "معرّف الرمز",
    "password was reset successfully": "تمت إعادة تعيين كلمة المرور بنجاح",
    "Reset password": "إعادة تعيين كلمة المرور",
    "New password": "كلمة المرور الجديدة",
    "content-type": "نوع المحتوى",
    "web-vitals": "مؤشرات الويب",
  },
};
