CREATE INDEX IF NOT EXISTS "store_idx" ON "collections" ("store_id");
CREATE INDEX IF NOT EXISTS "product_idx" ON "collections_products" ("product_id");
CREATE INDEX IF NOT EXISTS "collection_idx" ON "collections_products" ("collection_id");
CREATE UNIQUE INDEX IF NOT EXISTS "user_idx" ON "customers" ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "user_idx" ON "driver_managements" ("user_id");
CREATE INDEX IF NOT EXISTS "users_idsx" ON "driver_managements" ("users_ids");
CREATE UNIQUE INDEX IF NOT EXISTS "local_card_api_key_idx" ON "driver_managements" ("local_card_api_key_id");
CREATE UNIQUE INDEX IF NOT EXISTS "user_idx" ON "drivers" ("user_id");
CREATE INDEX IF NOT EXISTS "driver_managementx" ON "drivers" ("driver_management");
CREATE INDEX IF NOT EXISTS "merchant_idx" ON "local_card_keys" ("merchant_id");
CREATE INDEX IF NOT EXISTS "store_idx" ON "orders" ("store_id");
CREATE INDEX IF NOT EXISTS "store_statusx" ON "orders" ("store_status");
CREATE INDEX IF NOT EXISTS "driver_idx" ON "orders" ("driver_id");
CREATE INDEX IF NOT EXISTS "driver_statusx" ON "orders" ("driver_status");
CREATE INDEX IF NOT EXISTS "customer_idx" ON "orders" ("customer_id");
CREATE INDEX IF NOT EXISTS "customer_statusx" ON "orders" ("customer_status");
CREATE INDEX IF NOT EXISTS "accepted_proposalx" ON "orders" ("accepted_proposal");
CREATE INDEX IF NOT EXISTS "driver_managementx" ON "orders" ("driver_management");
CREATE INDEX IF NOT EXISTS "store_idx" ON "products" ("store_id");
CREATE UNIQUE INDEX IF NOT EXISTS "user_idx" ON "stores" ("user_id");
CREATE INDEX IF NOT EXISTS "users_idsx" ON "stores" ("users_ids");
CREATE INDEX IF NOT EXISTS "latx" ON "stores" ("lat");
CREATE INDEX IF NOT EXISTS "longx" ON "stores" ("long");
CREATE UNIQUE INDEX IF NOT EXISTS "local_card_api_key_id" ON "stores" ("local_card_api_key_id");
CREATE INDEX IF NOT EXISTS "customer_idx" ON "transactions" ("customer_id");
CREATE INDEX IF NOT EXISTS "store_idx" ON "transactions" ("store_id");
CREATE INDEX IF NOT EXISTS "order_idx" ON "transactions" ("order_id");
CREATE INDEX IF NOT EXISTS "store_idx" ON "order_products" ("store_id");
CREATE INDEX IF NOT EXISTS "order_idx" ON "order_products" ("order_id");
CREATE INDEX IF NOT EXISTS "product_idx" ON "product_descriptions" ("product_id");
CREATE INDEX IF NOT EXISTS "order_idx" ON "reports" ("order_id");
CREATE INDEX IF NOT EXISTS "driver_idx" ON "reports" ("driver_id");